### ISSUE TITLE
Setup mybatis

### ISSUE THREAD

**Issue by cbebry** [ZFGCCP/ZFGC3#1]

**Comment by MGZero** [comment]
https://github.com/ZFGCCP/ZFGC3/pull/5

**Comment by cbebry** [comment]
@MGZero  my only qualm with this is that the java class should be UpperCase style and the package name should be 100% lowercase. Eclipse is probably going to complain about at least one of these things.

**Comment by cbebry** [comment]
Needs redirection for db credentials in mybatis generator config.
See the following for examples: https://github.com/yyqian/spring-boot-mybatis-generator

**Comment by MGZero** [comment]
I don't seem to be able to create any kind of external configuration.  We're going to use application.properties for now to achieve what we need, will be distributing the needed information for that file to developers.
