### ISSUE TITLE
Figure out how to handle timezones

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/ZFGC3#10]
Timezones in smf are currently a bit of a mess.  It only stores the offset and doesn't actually tell you the name of the timezone.  We need to figure out how to best represent timezones in our database (some timezones share the same abbreviation - ACT for ex)

The forum time will default to GMT.  We'll calculate a user's local time based on this and their selected timezone.

**Comment by cbebry** [comment]
We want to store in IANA format, not offset and not three letter acronym.
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

https://www.iana.org/time-zones

For example, "America/Los_Angeles"
