### ISSUE TITLE
Create user profile summary front end

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/ZFGC3#31]
Load the user profile from the userprofile backend service (to be built)

See current zfgc for fields:
http://zfgc.com/forum/index.php?action=profile;u=3589

ui-router endpoint: #/profile/summary

Exclude the signature section for now.

Include the following (* represents field may be hidden by user, ** represents staff member only)

primary membergroup
avatar
display name
custom title
posts
personal text
reputation

gender*
age*
birthdate*

date registered
Primary IP**
Primary Host name**
local time
last active
username

email*
Facebook*
Skype*
AIM*
Hangouts*

**Comment by cbebry** [comment]
We should include the ui-router endpoints as part of these specs. For example, this one could be #/profile or #/user

**Comment by MGZero** [comment]
Yep, agree.  Will add this

**Comment by MGZero** [comment]
Wireframe attached
![profile - summary](https://cloud.githubusercontent.com/assets/1524901/21958140/64036790-da74-11e6-9594-308e3c4b6072.png)
