### ISSUE TITLE
Create forum index back end

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/ZFGC3#41]
Need a service to create the forum index:

http://zfgc.com/forum/

It should return a map of categories and forums.  Forum objects should contain the following:

name
description
list of child boards

If a category has no boards, or it cannot show any due to permissions (to come later), then do not return the category.

**Comment by cbebry** [comment]
Many of those things @MGZero described should be thought of in separate
components.

**Comment by MGZero** [comment]
@cbebry I removed them since we don't have threads and posts currently.  They will be in a future issue.

**Comment by cbebry** [comment]
👍
