### ISSUE TITLE
style forum index

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/ZFGC3#49]
Use zfgc.com/forum as a base.

Each category should have a border containing its name and its forums.

Each forum should contain its name and a list of child boards.

See screenshot below.
Use the existing styles created, extend them if needed (you'll definitely need to lol)
Each category should be collapsible, which can be done with angular-bootstrap's accordion directive
Take responsiveness into consideration if you find it possible at this stage.  The most important information to show on mobile is the forum name and description.  Other information can be hidden in a dropdown of some sort.

**Comment by cbebry** [comment]
Specifically zfgc.com/forum

**Comment by MGZero** [comment]
Attached a mockup for the layout.  Doesn't include a color scheme.

![mock up index](https://cloud.githubusercontent.com/assets/1524901/21746090/315afc98-d508-11e6-85d0-df7b0d7e14d1.png)

**Comment by MGZero** [comment]
@dcaruso19 There's some base styling now in global.css that you can use for this when you get to it
