### ISSUE TITLE
update widgets directive

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/ZFGC3#65]
make it not suck :)

**Comment by cbebry** [comment]
:+1:

Either wrap directives for the header template reuse, or go ng-transclude. Use collapse from https://github.com/angular-ui/bootstrap to avoid reinventing the wheel for bootstrap collapse functionality.
Write karma tests. Nothing is too trivial for a karma test. If you don't know how though, let me know and I'll lend a hand.

**Comment by MGZero** [comment]
Do we have access to this collapse currently or does it need to be added as a dependency?

**Comment by cbebry** [comment]
Angular-ui is currently not installed to zfgc as a bower dependency
