### ISSUE TITLE
Create registration front end

### ISSUE THREAD

**Issue by MGZero** [ZFGCCP/ZFGC3#9]
Create a new user form with the following fields (* indicates required)

Use the feature/user/login branch

*username
*displayname - if this is blank on submit, just populate it with the username
*password
*email address
*birthDate
timezone - also a dropdown.  Use the timezone lookup - Infer this from the client, but still allow them to change it.
*I agree to the terms and am 13 years of age or older checkbox

Back end service is in UsersController.java.  On failure, it will return a list of error messages.  Required fields errors are returned from this.

**Comment by cbebry** [comment]
What is location? Is this timezone?

**Comment by MGZero** [comment]
Location is just a string.  It can be an actual location, or it can be something you made up.  See my profile on current ZFGC for ex, it literally says "My Ass, NY."  Have not figured out how I want to handle timezones yet.

**Comment by cbebry** [comment]
Gotcha, alright. We probably want to handle timezones upfront rather than figuring them out later.

**Comment by MGZero** [comment]
Yep, will open an issue for that as well.

**Comment by cbebry** [comment]
Probably should allow picking it at registration time as well.

**Comment by MGZero** [comment]
updated issue with timezone and opened issue https://github.com/ZFGCCP/ZFGC3/issues/10
